#ifndef THREE_ADDR_CODE_H
#define THREE_ADDR_CODE_H

#include "ast.h"
#include <fstream>
#include <string>
#include <map>

using namespace std;

class ThreeAddrCodeGenerator {
private:
    ProgramNode* ast_root;
    ofstream& outcode;
    map<string, string> symbol_to_temp;
    int temp_count;
    int label_count;

public:
    ThreeAddrCodeGenerator(ProgramNode* root, ofstream& out)
        : ast_root(root), outcode(out), temp_count(0), label_count(0) {}

    void generate() {
        // Write header comments
        outcode << "//========== THREE ADDRESS CODE ==========" << endl;
        outcode << endl;
        outcode << "// This code was generated by a two-pass compiler" << endl;
        outcode << "// Format: " << endl;
        outcode << "// - t0, t1, etc. are temporary variables" << endl;
        outcode << "// - L0, L1, etc. are labels for jumps" << endl;
        outcode << "// - Operations follow the three-address code format" << endl;
        outcode << endl;
        outcode << "// Three Address Code" << endl;
        outcode << endl;
        
        // Generate code from AST
        if (ast_root) {
            ast_root->generate_code(outcode, symbol_to_temp, temp_count, label_count);
        }
        
        // Write footer
        outcode << endl;
        outcode << "//========== END OF CODE ==========" << endl;
        outcode << endl;
    }
};

#endif // THREE_ADDR_CODE_H
